# Generated by Django 3.1.5 on 2021-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecipe_proxy',
            name='labor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
