# Generated by Django 3.1.5 on 2021-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0002_auto_20210126_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecipe_proxy',
            name='unit_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
