# Generated by Django 3.1.5 on 2021-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0003_historicalrecipe_proxy_unit_labor_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecipe_proxy',
            name='labor_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecipe_line',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], default='grams', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalrecipe_proxy',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalrecipe_proxy',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], default='lbs', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe_line',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], default='grams', max_length=200),
        ),
        migrations.AlterField(
            model_name='weight_conversions',
            name='from_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], max_length=200),
        ),
        migrations.AlterField(
            model_name='weight_conversions',
            name='to_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], max_length=200),
        ),
    ]
