# Generated by Django 3.1.5 on 2021-05-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210530_1442'),
        ('making', '0003_historicalrecipe_proxy_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecipe_line',
            name='sku',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(_negated=True, product_type__in=['Finished Goods']), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.raw_material_proxy'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe_proxy',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe_line',
            name='sku',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, product_type__in=['Finished Goods']), on_delete=django.db.models.deletion.PROTECT, related_name='Recipe_sku_fk', to='operations.raw_material_proxy'),
        ),
    ]
