# Generated by Django 3.1.5 on 2021-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0004_auto_20210530_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecipe_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Making', 'Making')], max_length=100, null=True),
        ),
    ]
