# Generated by Django 3.1.5 on 2021-05-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0004_auto_20210530_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='labor_amount',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='labor_type',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='product_type',
        ),
    ]
