# Generated by Django 3.1.5 on 2021-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0005_historicalrecipe_proxy_labor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecipe_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making')], max_length=100, null=True),
        ),
    ]
