# Generated by Django 3.1.12 on 2022-02-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvoice',
            old_name='freight_charges',
            new_name='freight_cost',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='freight_charges',
            new_name='freight_cost',
        ),
    ]
