# Generated by Django 3.1.5 on 2021-02-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_historicalorder_cost_overlay_order_cost_overlay'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventory_onhand',
            name='unit_of_measure',
        ),
        migrations.AlterField(
            model_name='historicalinventory_onhand',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Bondo - 2nd Floor', 'Bondo - 2nd Floor'), ('MoonDance HQ - Workshop', 'MoonDance HQ - Workshop'), ('MoonDance HQ - Fulfillment Center', 'MoonDance HQ - Fulfillment Center')], max_length=200, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice_line',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Only needs to be populated if the manufacturer is different than the invoicing supplier.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.supplier', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inventory_onhand',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Bondo - 2nd Floor', 'Bondo - 2nd Floor'), ('MoonDance HQ - Workshop', 'MoonDance HQ - Workshop'), ('MoonDance HQ - Fulfillment Center', 'MoonDance HQ - Fulfillment Center')], max_length=200, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_line',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Only needs to be populated if the manufacturer is different than the invoicing supplier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Invoice_Manufacturer_fk', to='purchasing.supplier', verbose_name='Manufacturer'),
        ),
        migrations.RemoveField(
            model_name='inventory_onhand',
            name='unit_of_measure',
        ),
    ]
