# Generated by Django 3.1.5 on 2021-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_auto_20210227_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinvoice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Inventory Receipt'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoice_line',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Recipt Line'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date_invoiced', 'invoice'), 'verbose_name': 'Inventory Receipt', 'verbose_name_plural': 'Inventory Receipts'},
        ),
        migrations.AlterModelOptions(
            name='invoice_line',
            options={'ordering': ('sku',), 'verbose_name': 'Recipt Line', 'verbose_name_plural': 'Recipt Lines'},
        ),
        migrations.AlterField(
            model_name='historicalinventory_onhand',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Bondo - 2nd Floor', 'Bondo - 2nd Floor'), ('MoonDance - Workshop', 'MoonDance - Workshop'), ('MoonDance - Fulfillment Center', 'MoonDance - Fulfillment Center')], max_length=200, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='historicalinventory_onhand',
            name='to_location',
            field=models.CharField(blank=True, choices=[('Bondo - Garage', 'Bondo - Garage'), ('Bondo - 2nd Floor', 'Bondo - 2nd Floor'), ('MoonDance - Workshop', 'MoonDance - Workshop'), ('MoonDance - Fulfillment Center', 'MoonDance - Fulfillment Center')], max_length=200, null=True, verbose_name='Transfer To Location'),
        ),
        migrations.AlterField(
            model_name='inventory_onhand',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Bondo - 2nd Floor', 'Bondo - 2nd Floor'), ('MoonDance - Workshop', 'MoonDance - Workshop'), ('MoonDance - Fulfillment Center', 'MoonDance - Fulfillment Center')], max_length=200, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='inventory_onhand',
            name='to_location',
            field=models.CharField(blank=True, choices=[('Bondo - Garage', 'Bondo - Garage'), ('Bondo - 2nd Floor', 'Bondo - 2nd Floor'), ('MoonDance - Workshop', 'MoonDance - Workshop'), ('MoonDance - Fulfillment Center', 'MoonDance - Fulfillment Center')], max_length=200, null=True, verbose_name='Transfer To Location'),
        ),
    ]
