# Generated by Django 3.1.12 on 2022-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_historicalitem_transaction_history_item_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem_transaction_history',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('hours', 'hours'), ('minutes', 'minutes')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_transaction_history',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('hours', 'hours'), ('minutes', 'minutes')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalinventory_onhand',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Workshop', 'Workshop'), ('Fulfillment Area', 'Fulfillment Area'), ('Curing Room', 'Curing Room'), ('WomanCraft', 'WomanCraft'), ('FBA', 'FBA')], max_length=200, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='historicalinventory_onhand',
            name='to_location',
            field=models.CharField(blank=True, choices=[('Bondo - Garage', 'Bondo - Garage'), ('Workshop', 'Workshop'), ('Fulfillment Area', 'Fulfillment Area'), ('Curing Room', 'Curing Room'), ('WomanCraft', 'WomanCraft'), ('FBA', 'FBA')], max_length=200, null=True, verbose_name='Transfer To Location'),
        ),
        migrations.AlterField(
            model_name='historicalitem_transaction_history',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Workshop', 'Workshop'), ('Fulfillment Area', 'Fulfillment Area'), ('Curing Room', 'Curing Room'), ('WomanCraft', 'WomanCraft'), ('FBA', 'FBA')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory_onhand',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Workshop', 'Workshop'), ('Fulfillment Area', 'Fulfillment Area'), ('Curing Room', 'Curing Room'), ('WomanCraft', 'WomanCraft'), ('FBA', 'FBA')], max_length=200, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='inventory_onhand',
            name='to_location',
            field=models.CharField(blank=True, choices=[('Bondo - Garage', 'Bondo - Garage'), ('Workshop', 'Workshop'), ('Fulfillment Area', 'Fulfillment Area'), ('Curing Room', 'Curing Room'), ('WomanCraft', 'WomanCraft'), ('FBA', 'FBA')], max_length=200, null=True, verbose_name='Transfer To Location'),
        ),
        migrations.AlterField(
            model_name='item_transaction_history',
            name='location',
            field=models.CharField(choices=[('Bondo - Garage', 'Bondo - Garage'), ('Workshop', 'Workshop'), ('Fulfillment Area', 'Fulfillment Area'), ('Curing Room', 'Curing Room'), ('WomanCraft', 'WomanCraft'), ('FBA', 'FBA')], max_length=200),
        ),
    ]
