# Generated by Django 3.1.5 on 2021-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_auto_20210529_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice_line',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice_line',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('minutes', 'minutes')], max_length=200),
        ),
    ]
