# Generated by Django 3.1.5 on 2021-01-04 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('upc', models.CharField(max_length=200, null=True)),
                ('unit_of_measure', models.CharField(choices=[('grams', 'grams'), ('ounces', 'ounces')], default='grams', max_length=200)),
                ('quantity_onhand', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Master',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(max_length=200, null=True)),
                ('contact_email', models.CharField(max_length=200, null=True)),
                ('street_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(default='United States', max_length=200, null=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Shopify_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('shopify_product_id', models.CharField(max_length=200, unique=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopify_product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopify_product_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopify_product_sku_fk', to='operations.product')),
            ],
            options={
                'verbose_name': 'Shopify Product',
                'verbose_name_plural': 'Shopify Products',
            },
        ),
        migrations.CreateModel(
            name='Amazon_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('asin', models.CharField(max_length=200, unique=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_product_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amazon_product_product_fk', to='operations.product')),
            ],
            options={
                'verbose_name': 'Amazon Product',
                'verbose_name_plural': 'Amazon Products',
            },
        ),
        migrations.CreateModel(
            name='Supplier_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('supplier_sku', models.CharField(max_length=200)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_product_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Supplier_Product_product_fk', to='operations.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_product_supplier_fk', to='operations.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Product',
                'verbose_name_plural': 'Supplier Products',
                'unique_together': {('product', 'supplier_sku')},
            },
        ),
    ]
