# Generated by Django 3.1.5 on 2021-05-31 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Code",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Datetime Updated"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Finished Goods", "Finished Goods"),
                            ("WIP", "WIP"),
                            ("WIP - Labor", "WIP - Labor"),
                            ("Raw Materials", "Raw Materials"),
                            ("Labor", "Labor"),
                        ],
                        max_length=200,
                    ),
                ),
                ("family", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200, unique=True)),
                (
                    "freight_factor_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage adder to material cost. Use whole numbers with 2 decimals maximum.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "sales_channel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("All", "All"),
                            ("FBA", "FBA"),
                            ("MoonDance", "MoonDance"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_code_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_code_last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ("type", "family", "category"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Datetime Updated"),
                ),
                (
                    "sku",
                    models.CharField(max_length=200, unique=True, verbose_name="SKU"),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "upc",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="UPC"),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("grams", "grams"),
                            ("oz", "oz"),
                            ("lbs", "lbs"),
                            ("each", "each"),
                            ("minutes", "minutes"),
                        ],
                        default="lbs",
                        max_length=200,
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "unit_sales_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "unit_material_cost",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
                ),
                (
                    "unit_labor_cost",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
                (
                    "product_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Product_product_code_fk",
                        to="operations.product_code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Product List",
                "ordering": ("sku",),
            },
        ),
        migrations.CreateModel(
            name="Order_Cost_Overlay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Datetime Updated"),
                ),
                (
                    "sales_channel",
                    models.CharField(
                        choices=[
                            ("Shopify Website", "Shopify Website"),
                            ("Amazon FBA", "Amazon FBA"),
                            ("Amazon FBM", "Amazon FBM"),
                            ("POS", "POS"),
                        ],
                        max_length=200,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Fulfillment Labor", "Fulfillment Labor"),
                            ("Shipping Materials", "Shipping Materials"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "apply_to",
                    models.CharField(
                        choices=[
                            ("Each Order", "Each Order"),
                            ("Each Order Line", "Each Order Line"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "labor_hourly_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("labor_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "material_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_cost_overlay_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_cost_overlay_last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Overlay",
                "verbose_name_plural": "Cost Overlays",
                "ordering": ("sales_channel", "name"),
            },
        ),
        migrations.CreateModel(
            name="HistoricalRecipe_Line",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Datetime Updated"),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=12)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("grams", "grams"),
                            ("oz", "oz"),
                            ("lbs", "lbs"),
                            ("each", "each"),
                            ("minutes", "minutes"),
                        ],
                        default="grams",
                        max_length=200,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to=models.Q(_negated=True, product_code__type__in=["Finished Goods"]),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.product",
                    ),
                ),
                (
                    "sku_parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recipe Line",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Datetime Updated"),
                ),
                (
                    "sku",
                    models.CharField(db_index=True, max_length=200, verbose_name="SKU"),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "upc",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="UPC"),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("grams", "grams"),
                            ("oz", "oz"),
                            ("lbs", "lbs"),
                            ("each", "each"),
                            ("minutes", "minutes"),
                        ],
                        default="lbs",
                        max_length=200,
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "unit_sales_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "unit_material_cost",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
                ),
                (
                    "unit_labor_cost",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.product_code",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Product",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrder_Cost_Overlay",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Datetime Updated"),
                ),
                (
                    "sales_channel",
                    models.CharField(
                        choices=[
                            ("Shopify Website", "Shopify Website"),
                            ("Amazon FBA", "Amazon FBA"),
                            ("Amazon FBM", "Amazon FBM"),
                            ("POS", "POS"),
                        ],
                        max_length=200,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Fulfillment Labor", "Fulfillment Labor"),
                            ("Shipping Materials", "Shipping Materials"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "apply_to",
                    models.CharField(
                        choices=[
                            ("Each Order", "Each Order"),
                            ("Each Order Line", "Each Order Line"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "labor_hourly_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("labor_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "material_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cost Overlay",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Recipe_Line",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime Created"),
                ),
                (
                    "_last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Datetime Updated"),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=12)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("grams", "grams"),
                            ("oz", "oz"),
                            ("lbs", "lbs"),
                            ("each", "each"),
                            ("minutes", "minutes"),
                        ],
                        default="grams",
                        max_length=200,
                    ),
                ),
                (
                    "_created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_line_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "_last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_line_last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        limit_choices_to=models.Q(_negated=True, product_code__type__in=["Finished Goods"]),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Recipe_sku_fk",
                        to="operations.product",
                    ),
                ),
                (
                    "sku_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Recipe_sku_parent_fk",
                        to="operations.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Line",
                "verbose_name_plural": "Recipe Lines",
                "ordering": ("sku_parent", "sku"),
                "unique_together": {("sku", "sku_parent")},
            },
        ),
        migrations.CreateModel(
            name="Weight_Conversions",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_measure",
                    models.CharField(
                        choices=[
                            ("grams", "grams"),
                            ("oz", "oz"),
                            ("lbs", "lbs"),
                            ("each", "each"),
                            ("hours", "hours"),
                            ("minutes", "minutes"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "to_measure",
                    models.CharField(
                        choices=[
                            ("grams", "grams"),
                            ("oz", "oz"),
                            ("lbs", "lbs"),
                            ("each", "each"),
                            ("hours", "hours"),
                            ("minutes", "minutes"),
                        ],
                        max_length=200,
                    ),
                ),
                ("conversion_rate", models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                "verbose_name": "Weight Conversion",
                "verbose_name_plural": "Weight Conversions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrecipe_line",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Recipe",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe_line",
            options={
                "ordering": ("sku__product_code__family", "sku__sku"),
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipe",
            },
        ),
        migrations.RemoveField(
            model_name="product_code",
            name="sales_channel_type",
        ),
        migrations.AddField(
            model_name="historicalorder_cost_overlay",
            name="sales_percentage",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="sales_channel_type",
            field=models.CharField(
                choices=[("All", "All"), ("FBA", "FBA"), ("MoonDance", "MoonDance")], default="All", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="unit_freight_cost",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="order_cost_overlay",
            name="sales_percentage",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_channel_type",
            field=models.CharField(
                choices=[("All", "All"), ("FBA", "FBA"), ("MoonDance", "MoonDance")], default="All", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_freight_cost",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorder_cost_overlay",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="historicalorder_cost_overlay",
            name="sales_channel",
            field=models.CharField(
                choices=[
                    ("Shopify Retail", "Shopify Retail"),
                    ("Wholesale", "Wholesale"),
                    ("Amazon FBA", "Amazon FBA"),
                    ("Amazon FBM", "Amazon FBM"),
                    ("Farmers Market - Wake Forest", "Farmers Market - Wake Forest"),
                    ("Farmers Market - Durham", "Farmers Market - Durham"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder_cost_overlay",
            name="type",
            field=models.CharField(
                choices=[
                    ("Fulfillment Labor", "Fulfillment Labor"),
                    ("Shipping Materials", "Shipping Materials"),
                    ("Sales Channel Fees", "Sales Channel Fees"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hours", "hours"),
                    ("minutes", "minutes"),
                ],
                default="lbs",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecipe_line",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="operations.product",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecipe_line",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hours", "hours"),
                    ("minutes", "minutes"),
                ],
                default="grams",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="order_cost_overlay",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order_cost_overlay",
            name="sales_channel",
            field=models.CharField(
                choices=[
                    ("Shopify Retail", "Shopify Retail"),
                    ("Wholesale", "Wholesale"),
                    ("Amazon FBA", "Amazon FBA"),
                    ("Amazon FBM", "Amazon FBM"),
                    ("Farmers Market - Wake Forest", "Farmers Market - Wake Forest"),
                    ("Farmers Market - Durham", "Farmers Market - Durham"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="order_cost_overlay",
            name="type",
            field=models.CharField(
                choices=[
                    ("Fulfillment Labor", "Fulfillment Labor"),
                    ("Shipping Materials", "Shipping Materials"),
                    ("Sales Channel Fees", "Sales Channel Fees"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hours", "hours"),
                    ("minutes", "minutes"),
                ],
                default="lbs",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product_code",
            name="freight_factor_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage adder to material cost. Use whole numbers with 2 decimals maximum.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product_code",
            name="type",
            field=models.CharField(
                choices=[
                    ("Finished Goods", "Finished Goods"),
                    ("Raw Materials", "Raw Materials"),
                    ("Labor", "Labor"),
                    ("Labor Groups", "Labor Groups"),
                    ("Services", "Services"),
                    ("WIP", "WIP"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="recipe_line",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="Recipe_sku_fk", to="operations.product"
            ),
        ),
        migrations.AlterField(
            model_name="recipe_line",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hours", "hours"),
                    ("minutes", "minutes"),
                ],
                default="grams",
                max_length=200,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order_cost_overlay",
            unique_together={("name", "sales_channel")},
        ),
    ]
