# Generated by Django 3.1.5 on 2021-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='supplier_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupplier_product',
            name='supplier_sku_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_product',
            name='supplier_sku_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
