# Generated by Django 3.1.5 on 2021-01-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazon_product',
            options={'ordering': ('asin', 'seller_sku'), 'verbose_name': 'Amazon Product', 'verbose_name_plural': 'Amazon Products'},
        ),
        migrations.AddField(
            model_name='amazon_product',
            name='seller_sku',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amazon_product',
            name='asin',
            field=models.CharField(max_length=200),
        ),
    ]
