# Generated by Django 3.1.12 on 2022-02-08 16:03

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('hours', 'hours'), ('minutes', 'minutes')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each'), ('hours', 'hours'), ('minutes', 'minutes')], max_length=200),
        ),
        migrations.CreateModel(
            name='Product_Cost_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('standard_material_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('standard_freight_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('standard_labor_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_cost_history_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_cost_history_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Cost_History_sku_fk', to='operations.product')),
            ],
            options={
                'verbose_name': 'Product Cost History',
                'verbose_name_plural': 'Product Cost History',
                'ordering': ('start_date',),
            },
        ),
    ]
