# Generated by Django 3.1.5 on 2021-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalrecipe_line",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Recipe",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe_line",
            options={
                "ordering": ("sku_parent", "sku"),
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipe",
            },
        ),
        migrations.RemoveField(
            model_name="product_code",
            name="sales_channel_type",
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="sales_channel_type",
            field=models.CharField(
                choices=[("All", "All"), ("FBA", "FBA"), ("MoonDance", "MoonDance")],
                default="All",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_channel_type",
            field=models.CharField(
                choices=[("All", "All"), ("FBA", "FBA"), ("MoonDance", "MoonDance")],
                default="All",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hourly", "hourly"),
                ],
                default="lbs",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecipe_line",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hourly", "hourly"),
                ],
                default="grams",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hourly", "hourly"),
                ],
                default="lbs",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product_code",
            name="type",
            field=models.CharField(
                choices=[
                    ("Finished Goods", "Finished Goods"),
                    ("Raw Materials", "Raw Materials"),
                    ("Labor", "Labor"),
                    ("WIP", "WIP"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="recipe_line",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("grams", "grams"),
                    ("oz", "oz"),
                    ("lbs", "lbs"),
                    ("each", "each"),
                    ("hourly", "hourly"),
                ],
                default="grams",
                max_length=200,
            ),
        ),
    ]
