# Generated by Django 3.1.12 on 2022-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20220208_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='costing_method',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='costing_method',
            field=models.CharField(default='Manual', max_length=100),
        ),
    ]
