# Generated by Django 3.1.5 on 2021-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterials_management_proxy',
            name='recipe_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='recipe_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
