# Generated by Django 3.1.5 on 2021-01-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20210123_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_product_product_fk', to='operations.product'),
        ),
    ]
