# Generated by Django 3.1.5 on 2021-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_historicalorder_cost_overlay_order_cost_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfinished_goods_proxy',
            name='unit_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unit_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalraw_material_proxy',
            name='unit_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
