# Generated by Django 3.1.12 on 2022-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20220212_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='last_costing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_costing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='costing_method',
            field=models.CharField(choices=[('Manual Estimate', 'Manual Estimate'), ('Last Invoice', 'Last Invoice'), ('6 Month Average', '6 Month Average'), ('12 Month Average', '12 Month Average'), ('No Cost Found', 'No Cost Found'), ('Manual Override', 'Manual Override'), ('Recipe Cost Rollup', 'Recipe Cost Rollup')], default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costing_method',
            field=models.CharField(choices=[('Manual Estimate', 'Manual Estimate'), ('Last Invoice', 'Last Invoice'), ('6 Month Average', '6 Month Average'), ('12 Month Average', '12 Month Average'), ('No Cost Found', 'No Cost Found'), ('Manual Override', 'Manual Override'), ('Recipe Cost Rollup', 'Recipe Cost Rollup')], default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
