# Generated by Django 3.1.5 on 2021-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210605_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder_cost_overlay',
            name='sales_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order_cost_overlay',
            name='sales_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder_cost_overlay',
            name='sales_channel',
            field=models.CharField(choices=[('Shopify Website', 'Shopify Website'), ('Amazon FBA', 'Amazon FBA'), ('Amazon FBM', 'Amazon FBM'), ('Farmers Market', 'Farmers Market')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalorder_cost_overlay',
            name='type',
            field=models.CharField(choices=[('Fulfillment Labor', 'Fulfillment Labor'), ('Shipping Materials', 'Shipping Materials'), ('Transaction Fees', 'Transaction Fees')], max_length=200),
        ),
        migrations.AlterField(
            model_name='order_cost_overlay',
            name='sales_channel',
            field=models.CharField(choices=[('Shopify Website', 'Shopify Website'), ('Amazon FBA', 'Amazon FBA'), ('Amazon FBM', 'Amazon FBM'), ('Farmers Market', 'Farmers Market')], max_length=200),
        ),
        migrations.AlterField(
            model_name='order_cost_overlay',
            name='type',
            field=models.CharField(choices=[('Fulfillment Labor', 'Fulfillment Labor'), ('Shipping Materials', 'Shipping Materials'), ('Transaction Fees', 'Transaction Fees')], max_length=200),
        ),
    ]
