# Generated by Django 3.1.5 on 2021-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210109_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmaterials_management_proxy',
            name='recipe_cost',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='recipe_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recipe_cost',
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
