# Generated by Django 3.1.5 on 2021-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210108_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory_onhand',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200, verbose_name='Default Unit of Measure'),
        ),
        migrations.AddField(
            model_name='inventory_onhand',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200, verbose_name='Default Unit of Measure'),
        ),
    ]
