# Generated by Django 3.1.5 on 2021-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210123_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_product',
            name='sku_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
