# Generated by Django 3.1.5 on 2021-05-30 14:40

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_auto_20210530_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorder_cost_overlay',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cost Overlay'},
        ),
        migrations.AlterModelOptions(
            name='order_cost_overlay',
            options={'ordering': ('sales_channel', 'name'), 'verbose_name': 'Cost Overlay', 'verbose_name_plural': 'Cost Overlays'},
        ),
        migrations.AddField(
            model_name='historicalfinished_goods_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Making', 'Making')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallabor_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Making', 'Making')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Making', 'Making')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalraw_material_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Making', 'Making')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Making', 'Making')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLabor_Rates',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Updated')),
                ('labor_type', models.CharField(choices=[('Making', 'Making')], max_length=100)),
                ('labor_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_span', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('_created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Labor Rate',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Labor_Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('labor_type', models.CharField(choices=[('Making', 'Making')], max_length=100)),
                ('labor_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_span', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_rates_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_rates_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Labor Rate',
                'verbose_name_plural': 'Labor Rates',
                'ordering': ('labor_type', 'start_date', 'end_date'),
                'unique_together': {('labor_type', 'start_date', 'end_date')},
            },
        ),
    ]
