# Generated by Django 3.1.5 on 2021-01-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210104_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_code',
            options={'ordering': ('family', 'category'), 'verbose_name': 'Product Hierarchy', 'verbose_name_plural': 'Product Hierarchy'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AddField(
            model_name='product',
            name='freight_factor_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('ounces', 'ounces'), ('each', 'each')], default='grams', max_length=200),
        ),
    ]
