# Generated by Django 3.1.5 on 2021-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210116_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
