# Generated by Django 3.1.5 on 2021-01-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_auto_20210109_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier_product',
            options={'ordering': ('sku', 'supplier_sku'), 'verbose_name': 'Supplier Product', 'verbose_name_plural': 'Supplier Products'},
        ),
        migrations.RenameField(
            model_name='historicalsupplier_product',
            old_name='product',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='supplier_product',
            old_name='product',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='historicalinventory_onhand',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalmaterials_management_proxy',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='lbs', max_length=200, verbose_name='Default Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='lbs', max_length=200, verbose_name='Default Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='inventory_onhand',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='lbs', max_length=200, verbose_name='Default Unit of Measure'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier_product',
            unique_together={('sku', 'supplier_sku')},
        ),
        migrations.CreateModel(
            name='HistoricalBOM',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Updated')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=12)),
                ('unit_of_measure', models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('_created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.materials_management_proxy')),
                ('sku_parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.materials_management_proxy')),
            ],
            options={
                'verbose_name': 'historical Recipe',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=12)),
                ('unit_of_measure', models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOM_sku_Materials_Management_Proxy_fk', to='operations.materials_management_proxy')),
                ('sku_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOM_sku_parent_Materials_Management_Proxy_fk', to='operations.materials_management_proxy')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('sku_parent', 'sku'),
                'unique_together': {('sku', 'sku_parent')},
            },
        ),
    ]
