# Generated by Django 3.1.5 on 2021-01-23 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_amazon_product_sku_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Goods_Proxy',
            fields=[
            ],
            options={
                'verbose_name': 'Product - Finished Good',
                'verbose_name_plural': 'Product - Finished Goods',
                'ordering': ('sku',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.product',),
        ),
        migrations.AlterModelOptions(
            name='amazon_product',
            options={'ordering': ('product__sku', 'seller_sku', 'asin'), 'verbose_name': 'Integrations - Amazon', 'verbose_name_plural': 'Integrations - Amazon'},
        ),
        migrations.AlterModelOptions(
            name='historicalinventory_onhand',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Buying - Inventory Onhand'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Buying - Invoice'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoice_line',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Buying - Invoice Line'},
        ),
        migrations.AlterModelOptions(
            name='historicalrecipe_line',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Buying - Recipe Line'},
        ),
        migrations.AlterModelOptions(
            name='historicalrecipe_proxy',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Making - Recipe'},
        ),
        migrations.AlterModelOptions(
            name='historicalsupplier',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Buying - Supplier'},
        ),
        migrations.AlterModelOptions(
            name='historicalsupplier_product',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Buying - Supplier Product'},
        ),
        migrations.AlterModelOptions(
            name='inventory_onhand',
            options={'ordering': ('sku', 'location'), 'verbose_name': 'Buying - Inventory Onhand', 'verbose_name_plural': 'Buying - Inventory Onhand'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date_invoiced', 'invoice'), 'verbose_name': 'Buying - Invoice', 'verbose_name_plural': 'Buying - Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoice_line',
            options={'ordering': ('sku',), 'verbose_name': 'Buying - Invoice Line', 'verbose_name_plural': 'Buying - Invoice Lines'},
        ),
        migrations.AlterModelOptions(
            name='recipe_line',
            options={'ordering': ('sku_parent', 'sku'), 'verbose_name': 'Buying - Recipe Line', 'verbose_name_plural': 'Buying - Recipe Lines'},
        ),
        migrations.AlterModelOptions(
            name='recipe_proxy',
            options={'ordering': ('sku',), 'verbose_name': 'Making - Recipe', 'verbose_name_plural': 'Making - Recipes'},
        ),
        migrations.AlterModelOptions(
            name='shopify_product',
            options={'verbose_name': 'Integration - Shopify', 'verbose_name_plural': 'Integrations - Shopify'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Buying - Supplier', 'verbose_name_plural': 'Buying - Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplier_product',
            options={'ordering': ('sku', 'supplier_sku'), 'verbose_name': 'Buying - Supplier Product', 'verbose_name_plural': 'Buying - Supplier Products'},
        ),
        migrations.RemoveField(
            model_name='shopify_product',
            name='shopify_product_id',
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='barcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='customer_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='grams',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='handle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='inventory_management',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='inventory_policy',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='inventory_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='shopify_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='shopify_sku',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='tags',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify_product',
            name='variant_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalFinished_Goods_Proxy',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Updated')),
                ('product_type', models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('Raw Materials', 'Raw Materials')], max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200, verbose_name='SKU')),
                ('description', models.CharField(max_length=200)),
                ('upc', models.CharField(blank=True, max_length=200, null=True, verbose_name='UPC')),
                ('unit_of_measure', models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='lbs', max_length=200)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_material_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('unit_freight_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('product_notes', models.TextField(blank=True, null=True, verbose_name='Product Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('_created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.product_code')),
            ],
            options={
                'verbose_name': 'historical Product - Finished Good',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='amazon_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_product_product_fk', to='operations.finished_goods_proxy'),
        ),
    ]
