# Generated by Django 3.1.5 on 2021-05-30 18:42

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_auto_20210530_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLabor_Rate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Updated')),
                ('labor_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_span', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('_created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Labor Rate',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Labor_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('labor_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_span', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_rate_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_rate_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Labor Rate',
                'verbose_name_plural': 'Labor Rates',
                'ordering': ('labor_code', 'start_date', 'end_date'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='labor_rates',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='labor_rates',
            name='_created_by',
        ),
        migrations.RemoveField(
            model_name='labor_rates',
            name='_last_updated_by',
        ),
        migrations.CreateModel(
            name='Labor_Code',
            fields=[
            ],
            options={
                'verbose_name': 'Labor - Category',
                'verbose_name_plural': 'Labor - Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.product_code',),
        ),
        migrations.AddField(
            model_name='product_code',
            name='sales_channel_type',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('FBA', 'FBA'), ('MoonDance', 'MoonDance')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinished_goods_proxy',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallabor_proxy',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalraw_material_proxy',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='type',
            field=models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('WIP - Labor', 'WIP - Labor'), ('Raw Materials', 'Raw Materials'), ('Labor', 'Labor')], max_length=200),
        ),
        migrations.DeleteModel(
            name='HistoricalLabor_Rates',
        ),
        migrations.DeleteModel(
            name='Labor_Rates',
        ),
        migrations.AddField(
            model_name='labor_rate',
            name='labor_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_rates_labor_code_fk', to='operations.labor_code'),
        ),
        migrations.AddField(
            model_name='historicallabor_rate',
            name='labor_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.labor_code'),
        ),
        migrations.AlterUniqueTogether(
            name='labor_rate',
            unique_together={('labor_code', 'start_date', 'end_date')},
        ),
    ]
