# Generated by Django 3.1.5 on 2021-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210530_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabor_rates',
            name='sales_channel_type',
            field=models.CharField(choices=[('FBA', 'FBA'), ('MoonDance', 'MoonDance')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labor_rates',
            name='sales_channel_type',
            field=models.CharField(choices=[('FBA', 'FBA'), ('MoonDance', 'MoonDance')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalfinished_goods_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallabor_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallabor_rates',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallabor_rates',
            name='labor_type',
            field=models.CharField(choices=[('Soap Making', 'Soap Making')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalraw_material_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labor_rates',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labor_rates',
            name='labor_type',
            field=models.CharField(choices=[('Soap Making', 'Soap Making')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making')], max_length=100, null=True),
        ),
    ]
