# Generated by Django 3.1.5 on 2021-01-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210116_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier_product',
            name='sku',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.materials_management_proxy'),
        ),
        migrations.AlterField(
            model_name='supplier_product',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Supplier_Product_product_fk', to='operations.materials_management_proxy'),
        ),
    ]
