# Generated by Django 3.1.5 on 2021-01-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210123_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopify_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopify_product_sku_fk', to='operations.product'),
        ),
    ]
