# Generated by Django 3.1.5 on 2021-01-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0005_auto_20210109_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=12)),
                ('unit_of_measure', models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOM_sku_Materials_Management_Proxy_fk', to='operations.materials_management_proxy')),
                ('sku_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOM_sku_parent_Materials_Management_Proxy_fk', to='operations.materials_management_proxy')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('sku_parent', 'sku'),
                'unique_together': {('sku', 'sku_parent')},
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalBOM',
            new_name='HistoricalRecipe',
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
    ]
