# Generated by Django 3.1.12 on 2021-11-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210606_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder_cost_overlay',
            name='sales_channel',
            field=models.CharField(choices=[('Shopify Retail', 'Shopify Retail'), ('Wholesale', 'Wholesale'), ('Amazon FBA', 'Amazon FBA'), ('Amazon FBM', 'Amazon FBM'), ('Farmers Market - Wake Forest', 'Farmers Market - Wake Forest'), ('Farmers Market - Durham', 'Farmers Market - Durham')], max_length=200),
        ),
        migrations.AlterField(
            model_name='order_cost_overlay',
            name='sales_channel',
            field=models.CharField(choices=[('Shopify Retail', 'Shopify Retail'), ('Wholesale', 'Wholesale'), ('Amazon FBA', 'Amazon FBA'), ('Amazon FBM', 'Amazon FBM'), ('Farmers Market - Wake Forest', 'Farmers Market - Wake Forest'), ('Farmers Market - Durham', 'Farmers Market - Durham')], max_length=200),
        ),
    ]
