# Generated by Django 3.1.5 on 2021-01-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210106_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials_Management_Proxy',
            fields=[
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials Management',
                'ordering': ('sku',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.product',),
        ),
    ]
