# Generated by Django 3.1.5 on 2021-01-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210109_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product - Recipe'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sku',), 'verbose_name': 'Product - Recipe', 'verbose_name_plural': 'Product - Recipes'},
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='sku_parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Recipe_sku_fk', to='operations.materials_management_proxy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sku_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Recipe_sku_parent_fk', to='operations.product'),
        ),
    ]
