# Generated by Django 3.1.5 on 2021-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210123_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopify_product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopify_product',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
