# Generated by Django 3.1.5 on 2021-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210530_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalfinished_goods_proxy',
            old_name='labor_minutes',
            new_name='labor_amount',
        ),
        migrations.RenameField(
            model_name='historicallabor_proxy',
            old_name='labor_minutes',
            new_name='labor_amount',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='labor_minutes',
            new_name='labor_amount',
        ),
        migrations.RenameField(
            model_name='historicalraw_material_proxy',
            old_name='labor_minutes',
            new_name='labor_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='labor_minutes',
            new_name='labor_amount',
        ),
        migrations.AlterField(
            model_name='historicalfinished_goods_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallabor_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallabor_rates',
            name='labor_type',
            field=models.CharField(choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicallabor_rates',
            name='sales_channel_type',
            field=models.CharField(choices=[('All', 'All'), ('FBA', 'FBA'), ('MoonDance', 'MoonDance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalraw_material_proxy',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labor_rates',
            name='labor_type',
            field=models.CharField(choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labor_rates',
            name='sales_channel_type',
            field=models.CharField(choices=[('All', 'All'), ('FBA', 'FBA'), ('MoonDance', 'MoonDance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('Soap Making', 'Soap Making'), ('Soap Wrapping', 'Soap Wrapping'), ('Soap Boxing', 'Soap Boxing')], max_length=100, null=True),
        ),
    ]
