# Generated by Django 3.1.5 on 2021-01-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20210123_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopify_product',
            name='grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopify_product',
            name='handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopify_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopify_product_sku_fk', to='operations.finished_goods_proxy'),
        ),
        migrations.AlterField(
            model_name='shopify_product',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
