# Generated by Django 3.1.5 on 2021-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20210125_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopify_product',
            name='inventory_management',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopify_product',
            name='inventory_policy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
