# Generated by Django 3.1.5 on 2021-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20210106_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200, verbose_name='Default Unit of Measure'),
        ),
    ]
