# Generated by Django 3.1.5 on 2021-01-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20210116_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvoice_line',
            old_name='unit_cost',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='invoice_line',
            old_name='unit_cost',
            new_name='total_cost',
        ),
        migrations.AddField(
            model_name='historicalinvoice_line',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='lbs', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_line',
            name='unit_of_measure',
            field=models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='lbs', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='type',
            field=models.CharField(choices=[('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer')], default='Manufacturer', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer')], default='Manufacturer', max_length=200),
        ),
    ]
