# Generated by Django 3.1.5 on 2021-01-06 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0010_historicalinventory_onhand_historicalproduct_historicalsupplier_historicalsupplier_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterials_Management_Proxy',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Updated')),
                ('product_type', models.CharField(choices=[('Finished Goods', 'Finished Goods'), ('WIP', 'WIP'), ('Raw Materials', 'Raw Materials')], max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=200, verbose_name='SKU')),
                ('description', models.CharField(max_length=200)),
                ('upc', models.CharField(blank=True, max_length=200, null=True, verbose_name='UPC')),
                ('unit_of_measure', models.CharField(choices=[('grams', 'grams'), ('oz', 'oz'), ('lbs', 'lbs'), ('each', 'each')], default='grams', max_length=200, verbose_name='Default Unit of Measure')),
                ('quantity_onhand', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Sales Price')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('freight_factor_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('_created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.product_code')),
            ],
            options={
                'verbose_name': 'historical Material',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
