# Generated by Django 3.1.5 on 2021-01-25 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0010_auto_20210125_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('quantity', models.IntegerField()),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('product_bundle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Bundle_product_bundle_fk', to='operations.finished_goods_proxy')),
                ('product_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product_Bundle_product_used_fk', to='operations.finished_goods_proxy')),
            ],
            options={
                'verbose_name': 'Product - Bundle',
                'verbose_name_plural': 'Product - Bundles',
                'ordering': ('product_bundle__sku',),
            },
        ),
        migrations.DeleteModel(
            name='Product_Bundles',
        ),
    ]
