# Generated by Django 3.1.5 on 2021-01-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20210116_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice_line',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.supplier', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='invoice_line',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Invoice_Manufacturer_fk', to='operations.supplier', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.supplier', verbose_name='Invoicing Supplier'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice_line',
            name='sku',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.materials_management_proxy', verbose_name='MoonDance SKU'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Invoice_supplier_fk', to='operations.supplier', verbose_name='Invoicing Supplier'),
        ),
        migrations.AlterField(
            model_name='invoice_line',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Invoice_Line_sku_fk', to='operations.materials_management_proxy', verbose_name='MoonDance SKU'),
        ),
    ]
