# Generated by Django 3.1.5 on 2021-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_historicalmaterials_management_proxy'),
    ]

    operations = [

        migrations.RenameField(
            model_name='historicalmaterials_management_proxy',
            old_name='quantity_onhand',
            new_name='total_quantity_onhand',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='quantity_onhand',
            new_name='total_quantity_onhand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_onhand',
            new_name='total_quantity_onhand',
        ),


        migrations.RenameField(
            model_name='historicalmaterials_management_proxy',
            old_name='unit_price',
            new_name='unit_sales_price',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='unit_price',
            new_name='unit_sales_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='unit_sales_price',
        ),


        migrations.AddField(
            model_name='historicalmaterials_management_proxy',
            name='total_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='total_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),

        migrations.AddField(
            model_name='historicalmaterials_management_proxy',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),

        migrations.AddField(
            model_name='historicalmaterials_management_proxy',
            name='total_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='total_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
