# Generated by Django 3.1.5 on 2021-01-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_weight_conversions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight_conversions',
            name='_active',
        ),
        migrations.RemoveField(
            model_name='weight_conversions',
            name='_created',
        ),
        migrations.RemoveField(
            model_name='weight_conversions',
            name='_created_by',
        ),
        migrations.RemoveField(
            model_name='weight_conversions',
            name='_last_updated',
        ),
        migrations.RemoveField(
            model_name='weight_conversions',
            name='_last_updated_by',
        ),
    ]
