# Generated by Django 3.1.5 on 2021-01-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_auto_20210107_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterials_management_proxy',
            name='total_quantity_onhand',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total inventory across all locations.  Updates to quantites to should be done using the Inventory Onhand form below.', max_digits=12, null=True, verbose_name='Total Onhand Quantity'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials_management_proxy',
            name='unit_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='total_quantity_onhand',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total inventory across all locations.  Updates to quantites to should be done using the Inventory Onhand form below.', max_digits=12, null=True, verbose_name='Total Onhand Quantity'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity_onhand',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total inventory across all locations.  Updates to quantites to should be done using the Inventory Onhand form below.', max_digits=12, null=True, verbose_name='Total Onhand Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
