# Generated by Django 3.1.5 on 2021-01-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_auto_20210125_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduct_bundle_line',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bundle Item'},
        ),
        migrations.AlterModelOptions(
            name='product_bundle_line',
            options={'ordering': ('product_used__sku',), 'verbose_name': 'Bundle Item', 'verbose_name_plural': 'Bundle Items'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Product_product_code_fk', to='operations.product_code'),
        ),
    ]
