# Generated by Django 3.1.5 on 2021-01-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20210116_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier_product',
            unique_together={('supplier', 'supplier_sku')},
        ),
    ]
