# Generated by Django 3.1.5 on 2021-01-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20210119_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmaterials_management_proxy',
            name='freight_factor_percentage',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials_management_proxy',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials_management_proxy',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials_management_proxy',
            name='total_freight_cost',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials_management_proxy',
            name='total_material_cost',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='freight_factor_percentage',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='total_freight_cost',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='total_material_cost',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='freight_factor_percentage',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='total_freight_cost',
        ),
        migrations.RemoveField(
            model_name='historicalrecipe_proxy',
            name='total_material_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='freight_factor_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_freight_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_material_cost',
        ),
        migrations.AddField(
            model_name='historicalmaterials_management_proxy',
            name='product_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Product Notes'),
        ),
        migrations.AddField(
            model_name='historicalmaterials_management_proxy',
            name='unit_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Product Notes'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unit_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecipe_proxy',
            name='product_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Product Notes'),
        ),
        migrations.AddField(
            model_name='historicalrecipe_proxy',
            name='unit_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Product Notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
