# Generated by Django 3.1.5 on 2021-01-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20210107_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='unit_cost',
            new_name='unit_material_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_cost',
            new_name='unit_material_cost',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='total_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated using a percentage adder to account for inbound freight based upon type of material.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated using a percentage adder to account for inbound freight based upon type of material.', max_digits=12, null=True),
        ),
    ]
