# Generated by Django 3.1.5 on 2021-06-15 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('table', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('pie', 'pie'), ('donut', 'donut'), ('line', 'line'), ('spline', 'spline'), ('area', 'area'), ('column', 'column'), ('bar', 'bar')], max_length=200)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('show_legend', models.BooleanField(default=True)),
                ('show_title', models.BooleanField(default=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Charts',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('Operations', 'Operations'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], max_length=200)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Chart_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('is_default', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('field', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('filter', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('yaxis_prefix', models.CharField(choices=[('$', '$'), ('None', None)], max_length=200)),
                ('xaxis_type', models.CharField(choices=[('datetime', 'datetime'), ('category', 'category')], max_length=200)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_options_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_options_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automationtools.chart')),
            ],
            options={
                'verbose_name': 'Chart Option',
                'verbose_name_plural': 'Chart Options',
                'unique_together': {('chart', 'name', 'type')},
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='dashboard',
            field=models.ManyToManyField(to='automationtools.Dashboard'),
        ),
        migrations.CreateModel(
            name='Chart_Grouping',
            fields=[
            ],
            options={
                'verbose_name': 'Grouping Option',
                'verbose_name_plural': 'Grouping Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automationtools.chart_options',),
        ),
        migrations.CreateModel(
            name='Chart_XAxis',
            fields=[
            ],
            options={
                'verbose_name': 'X-Axis Option',
                'verbose_name_plural': 'X-Axis Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automationtools.chart_options',),
        ),
        migrations.CreateModel(
            name='Chart_YAxis',
            fields=[
            ],
            options={
                'verbose_name': 'Y-Axis Option',
                'verbose_name_plural': 'Y-Axis Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automationtools.chart_options',),
        ),
    ]
