# Generated by Django 3.1.5 on 2021-06-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationtools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='charts',
            field=models.ManyToManyField(to='automationtools.Chart'),
        ),
    ]
