# Generated by Django 3.1.5 on 2021-06-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationtools', '0003_auto_20210615_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='charts',
            field=models.ManyToManyField(blank=True, to='automationtools.Chart'),
        ),
    ]
