# Generated by Django 3.1.5 on 2021-06-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationtools', '0004_auto_20210615_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart_Grouping',
        ),
        migrations.DeleteModel(
            name='Chart_XAxis',
        ),
        migrations.DeleteModel(
            name='Chart_YAxis',
        ),
        migrations.AlterField(
            model_name='chart_options',
            name='filter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chart_options',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
