# Generated by Django 3.1.5 on 2021-06-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationtools', '0005_auto_20210615_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_Grouping',
            fields=[
            ],
            options={
                'verbose_name': 'Grouping Option',
                'verbose_name_plural': 'Grouping Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automationtools.chart_options',),
        ),
        migrations.CreateModel(
            name='Chart_XAxis',
            fields=[
            ],
            options={
                'verbose_name': 'X-Axis Option',
                'verbose_name_plural': 'X-Axis Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automationtools.chart_options',),
        ),
        migrations.CreateModel(
            name='Chart_YAxis',
            fields=[
            ],
            options={
                'verbose_name': 'Y-Axis Option',
                'verbose_name_plural': 'Y-Axis Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('automationtools.chart_options',),
        ),
        migrations.AlterField(
            model_name='chart_options',
            name='xaxis_type',
            field=models.CharField(blank=True, choices=[('datetime', 'datetime'), ('category', 'category')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chart_options',
            name='yaxis_prefix',
            field=models.CharField(blank=True, choices=[('$', '$'), (None, '----')], max_length=200, null=True),
        ),
    ]
