# Generated by Django 3.1.5 on 2021-06-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationtools', '0006_auto_20210615_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='table',
            field=models.CharField(max_length=200),
        ),
    ]
