# Generated by Django 3.1.5 on 2021-06-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationtools', '0007_auto_20210615_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_options',
            name='yaxis_decimals',
            field=models.IntegerField(default=0),
        ),
    ]
