# Generated by Django 3.1.5 on 2021-01-22 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Rate_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('state', models.CharField(max_length=200, unique=True)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rate_state_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rate_state_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'State Tax Rate',
                'verbose_name_plural': 'State Tax Rates',
                'ordering': ('state',),
            },
        ),
        migrations.CreateModel(
            name='Tax_Rate_County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('_last_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime Updated')),
                ('county', models.CharField(max_length=200)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('transit_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rate_county_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('_last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rate_county_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tax_Rate_County_state_fk', to='accounting.tax_rate_state')),
            ],
            options={
                'verbose_name': 'County Tax Rate',
                'verbose_name_plural': 'County Tax Rates',
                'ordering': ('state', 'county'),
                'unique_together': {('state', 'county')},
            },
        ),
    ]
