WITH line_items AS (
    SELECT
        jsonb_array_elements(line_items) as line_json,
        "fulfillments",
        "refunds",
        "total_tip_received",
        "original_total_duties_set",
        "current_total_duties_set",
        "admin_graphql_api_id",
        "shipping_lines",
        "billing_address",
        "client_details",
        "payment_details",
        "customer",
        "shipping_address",
        "id",
        "email",
        "closed_at",
        "created_at",
        "updated_at",
        "number",
        "note",
        "token",
        "gateway",
        "test",
        "total_price",
        "subtotal_price",
        "total_weight",
        "total_tax",
        "taxes_included",
        "currency",
        "financial_status",
        "confirmed",
        "total_discounts",
        "total_line_items_price",
        "cart_token",
        "buyer_accepts_marketing",
        "name",
        "referring_site",
        "landing_site",
        "cancelled_at",
        "cancel_reason",
        "total_price_usd",
        "checkout_token",
        "reference",
        "user_id",
        "location_id",
        "source_identifier",
        "source_url",
        "processed_at",
        "device_id",
        "phone",
        "customer_locale",
        "app_id",
        "browser_ip",
        "landing_site_ref",
        "order_number",
        "discount_applications",
        "discount_codes",
        "note_attributes",
        "payment_gateway_names",
        "processing_method",
        "checkout_id",
        "source_name",
        "fulfillment_status",
        "tax_lines",
        "tags",
        "contact_email",
        "order_status_url",
        "presentment_currency",
        "total_line_items_price_set",
        "total_discounts_set",
        "total_shipping_price_set",
        "subtotal_price_set",
        "total_price_set",
        "total_tax_set"
    FROM
        "public"."sales_orders_shopify"
)

SELECT
        id as order_id,
        name as order_number,
        fulfillment_status as order_fulfillment_status,   
        financial_status,
        line_json->>'id' as line_id,
        line_json->>'variant_id' as product_variant_id, 
        line_json->>'product_id' as product_variant_id, 
        line_json->>'title' as product_title, 
        line_json->>'name' as product_name,         
        line_json->>'sku' as product_sku,
        line_json->>'price' as unit_sales_price,
        line_json->>'quantity' as quantity,
        line_json->>'fulfillment_status' as line_fulfillment_status,  
        line_json->>'product_exists' as product_exists,  
        line_json->>'taxable' as is_taxable, 
        line_json->>'requires_shipping' as shipping_required, 
        line_json->>'grams' as shipping_unit_weight_grams, 

        --CUSTOMER
        customer->>'id' as customer_id,
        customer->>'first_name' as customer_first_name,
        customer->>'last_name' as customer_last_name,
        customer->'default_address'->>'company' as customer_company,
        customer->>'note' as customer_note,     
        customer->>'tax_exempt' as tax_exempt,
        customer->>'tags' as customer_tags,
        customer->>'email' as customer_email,
        customer->>'verified_email' as customer_verified_email,
        customer->>'state' as customer_account_status,
        customer->>'orders_count' as customer_orders_count,
        customer->>'total_spent' as customer_total_spent,
          
        --SHIPPING
        shipping_address->>'name' as ship_to_name,
        shipping_address->>'company' as ship_to_company,
        shipping_address->>'address1' as ship_to_address_1,
        shipping_address->>'city' as ship_to_city,
        shipping_address->>'province' as ship_to_state,
        shipping_address->>'zip' as ship_to_zip,
        shipping_address->>'country' as ship_to_country,
        shipping_address->>'phone' as ship_to_country,

        --KEY DATES
        created_at,
        updated_at,
        cancelled_at,
        processed_at,

        --MARKETING
        buyer_accepts_marketing as buyer_accepts_marketing,
        customer->>'accepts_marketing' as customer_accepts_marketing,
        customer->>'accepts_marketing_updated_at' as accepts_marketing_updated_at,
        referring_site,
        landing_site,
        client_details->'user_agent' as user_agent,
        source_name,
        processing_method,

        --OTHER
        contact_email,
        gateway,
        note as seller_notes,
        test as is_test,
        cancel_reason
FROM
    line_items